version: '3.4'
name: flowdance-azurefunctions

services:
  flowdance.azurefunctions:
    image: ${DOCKER_REGISTRY-}flowdanceazurefunctions
    build:
      context: .
      dockerfile: FlowDance.AzureFunctions/Dockerfile
