version: '3.4'
name: flowdance-azurefunctions

services:
  flowdance.azurefunctions:
    image: ${DOCKER_REGISTRY-}flowdanceazurefunctions
    build:
      context: .
      dockerfile: FlowDance.AzureFunctions/Dockerfile
    environment:
      - DurableDB_Connection=Server=192.168.1.65,1433;Database=DurableDB;User Id=sa;Password=Admin@123;
      - RabbitMq_Connection=amqp://guest:guest@192.168.1.65:5672
      - RabbitMq_StreamSettings__StreamPort=5552
      - RabbitMq_StreamSettings__LoadBalancer=true