name: flowdance-server

services:
  flowdance.server:
    image: ${DOCKER_REGISTRY-}flowdance
    build:
      context: .
      dockerfile: FlowDance.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AzureWebJobsStorage=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://host.docker.internal # https://www.connectionstrings.com/windows-azure/
      - FlowDanceDurableDB_Connection=Server=host.docker.internal,1433;TrustServerCertificate=True;Database=FlowDanceDurableDB;User Id=sa;Password=Admin@123;
      - FlowDanceCacheDB_Connection=Server=host.docker.internal,1433;TrustServerCertificate=True;Database=FlowDanceCacheDB;User Id=sa;Password=Admin@123;
      - RabbitMq_Connection=amqp://guest:guest@host.docker.internal:5672
      - RabbitMq_StreamSettings__StreamPort=5552
      - RabbitMq_StreamSettings__LoadBalancer=true
      - WEBSITE_HOSTNAME=localhost:80
    ports:
       - "31344:80" # Management UI
   