version: "3.9"
name: flowdance-server

services:
  flowdance.server:
    image: ${DOCKER_REGISTRY-}flowdance
    build:
      context: .
      dockerfile: FlowDance.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AzureWebJobsStorage=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://host.docker.internal # https://www.connectionstrings.com/windows-azure/
      - DurableDB_Connection=Server=host.docker.internal,1433;Database=DurableDB;User Id=sa;Password=Admin@123;
      - Redis_Connection=host.docker.internal:6379,password=Admin@123,ssl=False,abortConnect=False
      - RabbitMq_Connection=amqp://guest:guest@host.docker.internal:5672
      - RabbitMq_StreamSettings__StreamPort=5552
      - RabbitMq_StreamSettings__LoadBalancer=true
      - WEBSITE_HOSTNAME=localhost:80
    ports:
       - "31344:80" # Management UI
    # networks:
    #    - FDnet

# networks:
#   FDnet:
#     name: FlowDanceNetWork
#     external: true
