version: "3.9"
name: flowdance-server
    
services:

  flowdance:
    image: olahallvall/flowdance:1.0
    container_name: flowdance
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AzureWebJobsStorage=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://host.docker.internal # https://www.connectionstrings.com/windows-azure/
      - DurableDB_Connection=Server=host.docker.internal,1433;Database=DurableDB;User Id=sa;Password=Admin@123;
      - Redis_Connection=host.docker.internal:6379,password=Admin@123,ssl=False,abortConnect=False
      - RabbitMq_Connection=amqp://guest:guest@host.docker.internal:5672
      - RabbitMq_StreamSettings__StreamPort=5552
      - RabbitMq_StreamSettings__LoadBalancer=true
      - WEBSITE_HOSTNAME=localhost:80
    ports:
       - "31344:80" # Management UI
    depends_on:
      - rabbitmq
      - mssql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
       - "15672:15672" # Management UI
       - "5672:5672"   # Default RabbitMQ Port
       - "5552:5552"   # Steaming RabbitMQ Port

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    user: root
    hostname: mssql-db    
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Admin@123'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    ports: 
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
      
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass Admin@123
    volumes: 
      - ./data:/data
      
      
