version: "3.9"
name: flowdance-azurefunctions-deps
    
services:

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    #environment:
    #   RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_stream advertised_host 192.168.1.65
    container_name: rabbitmq
    ports:
       - "15672:15672" # Management UI
       - "5672:5672"   # Default RabbitMQ Port
       - "5552:5552"   # Steaming RabbitMQ Port
       
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    user: root
    hostname: mssql-db    
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Admin@123'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    ports: 
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
      
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass Admin@123
    volumes: 
      - ./data:/data
      
      
